### PR TITLE
CS fixes

### PR DESCRIPTION
**Pull request by bakura10**
Hi spiffy,

This is just a small PSR-1/2 fixes, nothing more. I didn't expect this module to be THAT big ôÔ !

Just a few things:
- Really, can't you remove the dependency to spiffy-test ? I couldn't run the unit tests because of this. I can't see a reason why you would need this.
- There are a lot of classes that ends up with name like "ProviderInterface" instead of "IdentityProviderInterface", "SomethingProviderInterface"... I usually dont' like this as it always needs to use aliases (otherwise, ProviderInterface means nothing). I think it would be a good idea to have more explicit names.
- Note sure that AbstractGuard should extend AbstractOptions, it's not an option class https://github.com/spiffyjr/spiffy-authorize/blob/master/src/SpiffyAuthorize/Guard/AbstractGuard.php#L10

### CODE REVIEW

**Comment by spiffyjr** [comment]
SpiffyTest makes setting up and using the service manager extremely easy with custom module/application settings just for testing. I add it by default to all my modules. I'll have to review this to determine whether or not I actually use it.

Feel free to submit a PR for the interfaces. I agree with you there.

The guards extending AbstractOptions has to do with the way I create services (which needs to be reviewed).

**Comment by bakura10** [comment]
I personally copy-paste this class across all the projects: https://github.com/zf-fr/zfr-rest/blob/master/tests/ZfrRestTest/Util/ServiceManagerFactory.php

It avoids adding a dependency just for that. Concerning test, I'd say to move the test config out of the "/config" folder. I mean, people using the module and opening the /config folder does not expect test config to be here imho.

**Comment by spiffyjr** [comment]
It's only a test dependency so I don't really see the issue. Also, that test.\* stuff in config/ is old - the new convention is for them to be in test/.

**Comment by bakura10** [comment]
Ha. I will issue a PR to remove them if you want.

**Comment by spiffyjr** [comment]
I'm going to update the tests now to make sure they run properly. I'll go ahead and do it.

**Comment by bakura10** [comment]
Ok thanks :).

**Pull request merged**
