### PR TITLE
Remove SpiffyTest dependency

### PR DESCRIPTION
**Pull request by bakura10**
Hi Spiffy,

This is my first step of the cleaning work (I've starting to clean Guards by reading carefully the whole code). I've been unable to run the tests, the problem was always Spiffy-Test, for some strange autoloading issues I couldn't debug.

So I simply get rid of it. I also:
- Made the Bootstrap.php more robust (it mimics what we do in all Doctrine ZF2 module).
- I've renamed "test" to "tests" as most modules use this (and it makes more sense, there is no one test :D). I can revert this back if you don't like it.
- I've changed all mock from ORM entity manager to an ObjectManager. This module should not rely on ORM I think.

### CODE REVIEW

**Comment by spiffyjr** [comment]
You did composer install --dev? Travis is running the tests fine.

**Comment by bakura10** [comment]
Yep. I don't know why. Anyway I replaced it by what we do in DoctrineModule. It's more or less the same thing.

**Comment by spiffyjr** [comment]
Yes, except _all_ my modules use spiffy-test for testing and I don't have to copy/paste duplicate files. If I make a change to the tests or add a new feature I update spiffy-test instead of everything else. I'd prefer to figure out why it doesn't run for you.

**Comment by bakura10** [comment]
Ok. I'll try to reinstall it and show you the error then.

**Comment by bakura10** [comment]
@spiffyjr:

PHP Fatal error:  Interface 'Zend\ModuleManager\Feature\ConfigProviderInterface' not found in /Users/michael/Sites/zend-skeleton-light/vendor/spiffy/spiffy-test/src/SpiffyTest/Module.php on line 11

I can't understand this error... I opened Module.php, nothing wrong. ZF is correctly loaded...

**Comment by spiffyjr** [comment]
https://github.com/zendframework/zf2/blob/master/library/Zend/ModuleManager/Feature/ConfigProviderInterface.php

That's really weird. I use that interface in just about every Module.php class I have.

**Comment by bakura10** [comment]
I know. First time I have this issue, I couldn't debug it... :/

**Comment by bakura10** [comment]
HAAA. I think I get it! Your spiffy-test does not have Module.php class at the root (which is the standard ZF2 way). Can't even know how travis tests can pass.

**Comment by bakura10** [comment]
Hmm... It still does not work (:

EDIT : really really really weird... I've tried everything. Moving the Module to the root... Still does not work, there seems to be a strange autoloading problem... :/. I've checked composer autoload file, seems fine.

**Comment by spiffyjr** [comment]
Check the file out on it's own and follow the steps in .travis.yml. That should work.

**Comment by bakura10** [comment]
Taht's already what I did :(. i can't get it... I'll try to delete everything and retry from scratch...

**Comment by bakura10** [comment]
I tried again following the travis.yml steps and it still fails. In fact, the problem is not understand why it fails, but how it worked for you.

1) SpiffyTest does not have Module.php class at the right place.
2) SpiffyAuthorize test config does not enable SpiffyTest module.
3) Travis is configured to run ../vendor/bin/phpunit, but I don't have such a folder in local.

**Comment by spiffyjr** [comment]
Module.php isn't in the "right place" because I use composer for autoloading. All my Module.php files are in PSR-0 locations and composer sets them up so the ModuleManager can still find them.

**Comment by bakura10** [comment]
I've tried a bit more today. In my code I can instantiate the SpiffyTest\Module class without this error. It just fails in CLI tools when launching the tests.

EDIT: If I remove the implements ConfigProviderInterface, I have those errors:

PHP Fatal error:  Class 'SpiffyTest\Framework\TestCase' not found in /Users/michael/Sites/zend-skeleton-light/vendor/spiffy/spiffy-authorize/test/SpiffyAuthorizeTest/ModuleTest.php on line 14

Can you try to install a fresh Spiffy-Authorize and Spiffy-Test and try if you have the same errors?

**Comment by spiffyjr** [comment]
Yes, when I get time today I can give that a shot.

**Comment by bakura10** [comment]
Have you been able to try it and reproduce my error? I couldn't give it more time, I really have A LOT of work until first week of october, but once it's done I'll have a few days off to work on this :).

**Comment by spiffyjr** [comment]
I'll do it now.

**Comment by spiffyjr** [comment]
``` sh
vagrant@precise64:/tmp$ git clone https://github.com/spiffyjr/spiffy-authorize.git
Cloning into 'spiffy-authorize'...
remote: Counting objects: 687, done.
remote: Compressing objects: 100% (332/332), done.
remote: Total 687 (delta 323), reused 640 (delta 282)
Receiving objects: 100% (687/687), 119.96 KiB, done.
Resolving deltas: 100% (323/323), done.
vagrant@precise64:/tmp$ cd spiffy-authorize/
vagrant@precise64:/tmp/spiffy-authorize$ ls
composer.json  composer.lock  config  doc  README.md  src  test  view
vagrant@precise64:/tmp/spiffy-authorize$ composer install --dev
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing zendframework/zend-stdlib (2.2.4)
    Loading from cache

  - Installing zendframework/zend-validator (2.2.4)
    Loading from cache

  - Installing zendframework/zend-escaper (2.2.4)
    Loading from cache

  - Installing zendframework/zend-uri (2.2.4)
    Loading from cache

  - Installing zendframework/zend-loader (2.2.4)
    Loading from cache

  - Installing zendframework/zend-http (2.2.4)
    Loading from cache

  - Installing doctrine/lexer (v1.0)
    Loading from cache

  - Installing doctrine/inflector (v1.0)
    Loading from cache

  - Installing doctrine/collections (v1.1)
    Loading from cache

  - Installing doctrine/cache (v1.1)
    Loading from cache

  - Installing doctrine/annotations (v1.1.2)
    Loading from cache

  - Installing doctrine/common (v2.4.1)
    Loading from cache

  - Installing symfony/console (v2.3.4)
    Loading from cache

  - Installing doctrine/dbal (v2.4.0)
    Loading from cache

  - Installing doctrine/orm (v2.4.0)
    Loading from cache

  - Installing mockery/mockery (0.8.0)
    Loading from cache

  - Installing phpunit/php-token-stream (1.2.0)
    Loading from cache

  - Installing symfony/yaml (v2.3.4)
    Loading from cache

  - Installing phpunit/php-text-template (1.1.4)
    Loading from cache

  - Installing phpunit/phpunit-mock-objects (1.2.3)
    Loading from cache

  - Installing phpunit/php-timer (1.0.5)
    Loading from cache

  - Installing phpunit/php-file-iterator (1.3.3)
    Loading from cache

  - Installing phpunit/php-code-coverage (1.2.12)
    Loading from cache

  - Installing phpunit/phpunit (3.7.24)
    Loading from cache

  - Installing zendframework/zend-servicemanager (2.2.4)
    Loading from cache

  - Installing zendframework/zend-eventmanager (2.2.4)
    Loading from cache

  - Installing zendframework/zend-mvc (2.2.4)
    Loading from cache

  - Installing zendframework/zend-modulemanager (2.2.4)
    Loading from cache

  - Installing spiffy/spiffy-test (dev-master a5de9d0)
    Cloning a5de9d0ad08f7e61b53c3d533fcb1090962be9b3

  - Installing zendframework/zend-authentication (2.2.4)
    Loading from cache

  - Installing zendframework/zend-config (2.2.4)
    Loading from cache

  - Installing zendframework/zend-console (2.2.4)
    Loading from cache

  - Installing zendframework/zend-version (2.2.4)
    Loading from cache

  - Installing zendframework/zend-debug (2.2.4)
    Loading from cache

  - Installing zendframework/zend-developer-tools (dev-master 9b93113)
    Cloning 9b9311311fdb562494f89e62eb4649d687b58364

  - Installing zendframework/zend-filter (2.2.4)
    Loading from cache

  - Installing zendframework/zend-inputfilter (2.2.4)
    Loading from cache

  - Installing zendframework/zend-form (2.2.4)
    Loading from cache

  - Installing zendframework/zend-permissions-acl (2.2.4)
    Loading from cache

  - Installing zendframework/zend-permissions-rbac (2.2.4)
    Loading from cache

  - Installing zendframework/zend-math (2.2.4)
    Loading from cache

  - Installing zendframework/zend-json (2.2.4)
    Loading from cache

  - Installing zendframework/zend-serializer (2.2.4)
    Loading from cache

  - Installing zendframework/zend-session (2.2.4)
    Loading from cache

  - Installing zendframework/zend-view (2.2.4)
    Loading from cache

zendframework/zend-validator suggests installing zendframework/zend-db (Zend\Db component)
zendframework/zend-validator suggests installing zendframework/zend-i18n (Zend\I18n component to allow translation of validation error messages as well as to use the various Date validators)
zendframework/zend-validator suggests installing zendframework/zend-resources (Translations of validator messages)
symfony/console suggests installing symfony/event-dispatcher ()
phpunit/phpunit suggests installing phpunit/php-invoker (>=1.1.0,<1.2.0)
zendframework/zend-servicemanager suggests installing zendframework/zend-di (Zend\Di component)
zendframework/zend-mvc suggests installing zendframework/zend-di (Zend\Di component)
zendframework/zend-mvc suggests installing zendframework/zend-i18n (Zend\I18n component for translatable segments)
zendframework/zend-mvc suggests installing zendframework/zend-text (Zend\Text component)
zendframework/zend-authentication suggests installing zendframework/zend-crypt (Zend\Crypt component)
zendframework/zend-authentication suggests installing zendframework/zend-db (Zend\Db component)
zendframework/zend-debug suggests installing ext/xdebug (XDebug, for better backtrace output)
zendframework/zend-developer-tools suggests installing bjyoungblood/bjy-profiler (Version: dev-master, allows the usage of the (Zend) Db collector.)
zendframework/zend-developer-tools suggests installing ocramius/ocra-service-manager (OcraServiceManager can help you track dependencies within your application.)
zendframework/zend-filter suggests installing zendframework/zend-crypt (Zend\Crypt component)
zendframework/zend-filter suggests installing zendframework/zend-i18n (Zend\I18n component)
zendframework/zend-form suggests installing zendframework/zendservice-recaptcha (ZendService\ReCaptcha component)
zendframework/zend-math suggests installing ircmaxell/random-lib (Fallback random byte generator for Zend\Math\Rand if OpenSSL/Mcrypt extensions are unavailable)
zendframework/zend-json suggests installing zendframework/zend-server (Zend\Server component)
Generating autoload files
vagrant@precise64:/tmp/spiffy-authorize$ cd test/
vagrant@precise64:/tmp/spiffy-authorize/test$ ../vendor/bin/phpunit
PHPUnit 3.7.24 by Sebastian Bergmann.

Configuration read from /tmp/spiffy-authorize/test/phpunit.xml

...................................................

Time: 196 ms, Memory: 14.25Mb

OK (51 tests, 114 assertions)
vagrant@precise64:/tmp/spiffy-authorize/test$
```

**Comment by bakura10** [comment]
Thanks for trying it :).

**Comment by spiffyjr** [comment]
Does that not work if you do exactly what I did?

**Comment by bakura10** [comment]
I'm sorry, but I did it again, with a fresh install of Spiffy Test and Spiffy Authorize on my mac, and it still does not work. I did:

`php composer.phar install --dev` (I also tried with the flag --prefer-source), and here is the full error:

``` bash
PHP Fatal error:  Interface 'Zend\ModuleManager\Feature\ConfigProviderInterface' not found in /Users/michael/Sites/zend-skeleton-light/vendor/spiffy/spiffy-test/src/SpiffyTest/Module.php on line 11
PHP Stack trace:
PHP   1. {main}() /usr/local/php5-20130210-223618/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /usr/local/php5-20130210-223618/bin/phpunit:46
PHP   3. PHPUnit_TextUI_Command->run() /usr/local/php5-20130210-223618/lib/php/PHPUnit/TextUI/Command.php:129
PHP   4. PHPUnit_TextUI_Command->handleArguments() /usr/local/php5-20130210-223618/lib/php/PHPUnit/TextUI/Command.php:138
PHP   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/local/php5-20130210-223618/lib/php/PHPUnit/TextUI/Command.php:606
PHP   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/local/php5-20130210-223618/lib/php/PHPUnit/TextUI/Command.php:778
PHP   7. PHPUnit_Util_Fileloader::load() /usr/local/php5-20130210-223618/lib/php/PHPUnit/Util/Fileloader.php:76
PHP   8. include_once() /usr/local/php5-20130210-223618/lib/php/PHPUnit/Util/Fileloader.php:92
PHP   9. require() /Users/michael/Sites/zend-skeleton-light/vendor/spiffy/spiffy-authorize/test/bootstrap.php:16

Fatal error: Interface 'Zend\ModuleManager\Feature\ConfigProviderInterface' not found in /Users/michael/Sites/zend-skeleton-light/vendor/spiffy/spiffy-test/src/SpiffyTest/Module.php on line 11

Call Stack:
    0.0002     226040   1. {main}() /usr/local/php5-20130210-223618/bin/phpunit:0
    0.0031     503112   2. PHPUnit_TextUI_Command::main() /usr/local/php5-20130210-223618/bin/phpunit:46
    0.0031     503344   3. PHPUnit_TextUI_Command->run() /usr/local/php5-20130210-223618/lib/php/PHPUnit/TextUI/Command.php:129
    0.0032     503776   4. PHPUnit_TextUI_Command->handleArguments() /usr/local/php5-20130210-223618/lib/php/PHPUnit/TextUI/Command.php:138
    0.0186     849160   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/local/php5-20130210-223618/lib/php/PHPUnit/TextUI/Command.php:606
    0.0193     857632   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/local/php5-20130210-223618/lib/php/PHPUnit/TextUI/Command.php:778
    0.0194     857856   7. PHPUnit_Util_Fileloader::load() /usr/local/php5-20130210-223618/lib/php/PHPUnit/Util/Fileloader.php:76
    0.0195     861736   8. include_once('/Users/michael/Sites/zend-skeleton-light/vendor/spiffy/spiffy-authorize/test/bootstrap.php') /usr/local/php5-20130210-223618/lib/php/PHPUnit/Util/Fileloader.php:92
    0.0199     891744   9. require('/Users/michael/Sites/zend-skeleton-light/vendor/spiffy/spiffy-test/src/SpiffyTest/Module.php') /Users/michael/Sites/zend-skeleton-light/vendor/spiffy/spiffy-authorize/test/bootstrap.php:16
```

**Comment by bakura10** [comment]
SpiffyTest really can't find any ZF2 classes, there is indeed a big problem in autoloading in this module. In fact, the Module.php class looks really obscure to me. It seems it makes a lot of assumptions about ZF2 path, so I think it messes up a lot of things.

**Comment by bakura10** [comment]
I'd suggest you'd drastically simplify SpiffyTest Module.php :).

**Comment by spiffyjr** [comment]
The Module.php is slightly more than the typical Bootstrap.php that goes with most ZF2 tests.

**Comment by spiffyjr** [comment]
See: http://framework.zend.com/manual/2.0/en/user-guide/unit-testing.html which is what I used to write spiffy test.

**Comment by spiffyjr** [comment]
Are you using the phpunit included in vendor or your own phpunit?

**Comment by bakura10** [comment]
I have my own phpunit. I would not trust this init stuff, looks so strange ôÔ.

**Comment by spiffyjr** [comment]
Strange? It's in the official docs! The only thing I added was optional test-specific application.config.php and module.config.php files!

Try running vendor/bin/phpunit and see if it works with that. I'm curious.

**Comment by bakura10** [comment]
I don't have any phpunit in the bin folder. In fact, I'm trying to udnerstand why you need all this code for spiffy-test, while most of the features you ask for spiffy-test, we replicate it in a single class in most Doctrine modules. I can understand you in having this class in a module instead of duplicating it in all projects, but I can't see why Spiffytest is so complicated :(.

**Comment by spiffyjr** [comment]
How do you not have a phpunit in the bin folder? It's a requirement (see require-dev).

**Comment by spiffyjr** [comment]
Can you paste the entire composer install command and output?

**Comment by bakura10** [comment]
Mmhhh I do a simple composer.phar install --dev

But obviously all the dev packages are not downloaded... Neither mockery nor phpunit :(. I need to manually add them in my root composer.json file.

This thing's gonna make me crazy.

**Comment by bakura10** [comment]
GRRR I really can't understand WHY when I make a composer update --dev it does not download the packages that are in require-dev of the Spiffy-authorize.

This command is still valid in newer versions of composer?

**Comment by spiffyjr** [comment]
Yes, still valid.

Is something in your root composer.json messing with things?

**Pull request closed without merging**
