### PR TITLE
Cleanup identity provider

### PR DESCRIPTION
**Pull request by bakura10**
Rename identity provider classes (you were using both AuthenticationProvider and IdentityProvider across the code base, but IdentityProvider makes more sense).

Also properly handle injection of default and guest role from module options.

This will likely cause some conflicts when you will merge https://github.com/spiffyjr/spiffy-authorize/pull/8

all tests have been updated and pass

### CODE REVIEW

**Comment by spiffyjr** [comment]
AuthenticationProvider is a specific type of IdentityProvider that uses Zend\Authentication\AuthenticationService to get the identity.

**Comment by bakura10** [comment]
AuthenticationIdentityProvider ? :D

Envoyé de mon iPhone

**Comment by spiffyjr** [comment]
And this?

**Comment by bakura10** [comment]
Should be ok @spiffyjr . I keep with AuthenticationProvider name.

**Pull request merged**
