### PR TITLE
Guards

### PR DESCRIPTION
**Pull request by bakura10**
Cleaning for guards (note: I'll update test once the other PR is merged).
- Remove unused interface.
- Start to move factories to a "Factory" namespace, otherwise if we keep eveyrthing in Service, Factories are mixed up with real services.
- AbstractGuard no longer extends from AbstractOptions because they are not options classes. The rules and authorization service are injected inside the guards.
- Set dependency to ZF 2.2 as it provides lot of traits that help reduce code (if this is a problem I can revert it back, but as we'll likely have a dependency to DoctirneModule 1.0 which provides A LOT of nice things to work more easily with both ODM and ORM, and that DoctrineModule 1.0 has dependency to 2.2, let's start to use it now ;-)).

One question for you Spiffy: I don't understand guard. You are talking about "permissions", but in all your examples, you map a route to a role. Is this expected?

EDIt : I4ve added some tests. This PR is built on top on the other one, so you should first merge the other one =).

RouteParamsGuard is untested currently. I wonder if this is a good idea though? It will obviously tie the security configuration to the route definition, not sure if this is really something we want no?

### CODE REVIEW

**Comment by spiffyjr** [comment]
I'll review this in more detail on Monday/Tuesday. It's a big one. :D

**Comment by bakura10** [comment]
oops. It does not have 50 files in fact lol. It's just because I merged the other PR (the tests one) in this one becuase I couldn't run tests with SpiffyTest :D. In fact the PR is much lighter :).

**Comment by spiffyjr** [comment]
What's up with this?

**Comment by bakura10** [comment]
Don't merge it, I'll close it once I will be done with all the changes with the guards.

**Pull request closed without merging**
